export const divisions = {
  status: {
    code: 200,
    message: "ok",
    date: "Sat, 20 Jan 2024 08:32:10 GMT",
  },
  data: [
    {
      _id: "barishal",
      division: "Barishal",
      divisionbn: "\u09ac\u09b0\u09bf\u09b6\u09be\u09b2",
      coordinates: "22.3811, 90.3372",
    },
    {
      _id: "chattogram",
      division: "Chattogram",
      divisionbn: "\u099a\u099f\u09cd\u099f\u0997\u09cd\u09b0\u09be\u09ae",
      coordinates: "23.1793, 91.9882",
    },
    {
      _id: "dhaka",
      division: "Dhaka",
      divisionbn: "\u09a2\u09be\u0995\u09be",
      coordinates: "23.9536, 90.1495",
    },
    {
      _id: "khulna",
      division: "Khulna",
      divisionbn: "\u0996\u09c1\u09b2\u09a8\u09be",
      coordinates: "22.8088, 89.2467",
    },
    {
      _id: "mymensingh",
      division: "Mymensingh",
      divisionbn: "\u09ae\u09af\u09bc\u09ae\u09a8\u09b8\u09bf\u0982\u09b9",
      coordinates: "24.7136, 90.4502",
    },
    {
      _id: "rajshahi",
      division: "Rajshahi",
      divisionbn: "\u09b0\u09be\u099c\u09b6\u09be\u09b9\u09c0",
      coordinates: "24.7106, 88.9414",
    },
    {
      _id: "rangpur",
      division: "Rangpur",
      divisionbn: "\u09b0\u0982\u09aa\u09c1\u09b0",
      coordinates: "25.8483, 88.9414",
    },
    {
      _id: "sylhet",
      division: "Sylhet",
      divisionbn: "\u09b8\u09bf\u09b2\u09c7\u099f",
      coordinates: "24.7050, 91.6761",
    },
  ],
};
export const individual_divisions = {
  barishal: {
    status: {
      code: 200,
      message: "ok",
      date: "Sat, 20 Jan 2024 08:32:10 GMT",
    },
    data: [
      {
        _id: "barguna",
        district: "Barguna",
        coordinates: "22.0953, 90.1121",
        upazilla: [
          "Taltali",
          "Bamna",
          "Patharghata",
          "Barguna Sadar",
          "Amtali",
          "Betagi",
        ],
      },
      {
        _id: "barishal",
        district: "Barishal",
        coordinates: "22.7022, 90.3696",
        upazilla: [
          "Hizla",
          "Bakerganj",
          "Banaripara",
          "Muladi",
          "Wazirpur",
          "Agailjhara",
          "Babuganj",
          "Barisal Sadar",
          "Mehendiganj",
          "Gaurnadi",
        ],
      },
      {
        _id: "bhola",
        district: "Bhola",
        coordinates: "22.1785, 90.7101",
        upazilla: [
          "Lalmohan",
          "Manpura",
          "Bhola Sadar",
          "Tazumuddin",
          "Burhanuddin",
          "Char Fasson",
          "Daulatkhan",
        ],
      },
      {
        _id: "jhalokati",
        district: "Jhalokati",
        coordinates: "22.5721, 90.1870",
        upazilla: ["Rajapur", "Nalchhiti", "Kathalia", "Jhalokati Sadar"],
      },
      {
        _id: "patuakhali",
        district: "Patuakhali",
        coordinates: "22.2249, 90.4548",
        upazilla: [
          "Patuakhali Sadar",
          "Mirzaganj",
          "Dashmina",
          "Bauphal",
          "Rangabali",
          "Kalapara",
          "Dumki",
          "Galachipa",
        ],
      },
      {
        _id: "pirojpur",
        district: "Pirojpur",
        coordinates: "22.5791, 89.9759",
        upazilla: [
          "Kawkhali",
          "Nazirpur",
          "Mathbaria",
          "Pirojpur Sadar",
          "Bhandaria",
          "Nesarabad (Swarupkati)",
          "Indurkani",
        ],
      },
    ],
  },
  chattogram: {
    status: {
      code: 200,
      message: "ok",
      date: "Sat, 20 Jan 2024 08:32:11 GMT",
    },
    data: [
      {
        _id: "bandarban",
        district: "Bandarban",
        coordinates: "21.8311, 92.3686",
        upazilla: [
          "Naikhongchhari",
          "Bandarban Sadar",
          "Thanchi",
          "Rowangchhari",
          "Ali Kadam",
          "Lama",
          "Ruma",
        ],
      },
      {
        _id: "brahmanbaria",
        district: "Brahmanbaria",
        coordinates: "23.9608, 91.1115",
        upazilla: [
          "Nabinagar",
          "Nasirnagar",
          "Sarail",
          "Brahmanbaria Sadar",
          "Ashuganj",
          "Bijoynagar",
          "Bancharampur",
          "Kasba",
          "Akhaura",
        ],
      },
      {
        _id: "chandpur",
        district: "Chandpur",
        coordinates: "23.2513, 90.8518",
        upazilla: [
          "Kachua",
          "Chandpur Sadar",
          "Shahrasti",
          "Haziganj",
          "Matlab Dakshin",
          "Faridganj",
          "Haimchar",
          "Matlab Uttar",
        ],
      },
      {
        _id: "chattogram",
        district: "Chattogram",
        coordinates: "22.5150, 91.7539",
        upazilla: [
          "Patiya",
          "Rangunia",
          "Anwara",
          "Boalkhali",
          "Raozan",
          "Hathazari",
          "Banshkhali",
          "Mirsharai",
          "Satkania",
          "Sitakunda",
          "Karnaphuli",
          "Sandwip",
          "Chandanaish",
          "Fatikchhari",
          "Lohagara",
        ],
      },
      {
        _id: "cox's bazar",
        district: "Cox's Bazar",
        coordinates: "21.5641, 92.0282",
        upazilla: [
          "Chakaria",
          "Ramu",
          "Kutubdia",
          "Pekua",
          "Teknaf",
          "Maheshkhali",
          "Cox's Bazar Sadar",
          "Ukhia",
        ],
      },
      {
        _id: "cumilla",
        district: "Cumilla",
        coordinates: "23.4576, 91.1809",
        upazilla: [
          "Meghna",
          "Chauddagram",
          "Cumilla Adarsha Sadar",
          "Brahmanpara",
          "Burichang",
          "Lalmai",
          "Nangalkot",
          "Cumilla Sadar Dakshin",
          "Laksam",
          "Monohargonj",
          "Daudkandi",
          "Chandina",
          "Barura",
          "Homna",
          "Muradnagar",
          "Titas",
          "Debidwar",
        ],
      },
      {
        _id: "feni",
        district: "Feni",
        coordinates: "22.9409, 91.4067",
        upazilla: [
          "Chhagalnaiya",
          "Sonagazi",
          "Daganbhuiyan",
          "Fulgazi",
          "Parshuram",
          "Feni Sadar",
        ],
      },
      {
        _id: "khagrachari",
        district: "Khagrachari",
        coordinates: "23.1322, 91.9490",
        upazilla: [
          "Dighinala",
          "Manikchhari",
          "Panchhari",
          "Matiranga",
          "Lakshmichhari",
          "Mahalchhari",
          "Ramgarh",
          "Khagrachhari Sadar",
        ],
      },
      {
        _id: "lakshmipur",
        district: "Lakshmipur",
        coordinates: "22.9447, 90.8282",
        upazilla: [
          "Lakshmipur Sadar",
          "Kamalnagar",
          "Ramganj",
          "Ramgati",
          "Raipur",
        ],
      },
      {
        _id: "noakhali",
        district: "Noakhali",
        coordinates: "22.8724, 91.0973",
        upazilla: [
          "Begumganj",
          "Companiganj",
          "Hatiya",
          "Subarnachar",
          "Noakhali Sadar",
          "Kabirhat",
          "Senbagh",
          "Sonaimuri",
          "Chatkhil",
        ],
      },
      {
        _id: "rangamati",
        district: "Rangamati",
        coordinates: "22.7324, 92.2985",
        upazilla: [
          "Kaptai",
          "Barkal",
          "Langadu",
          "Rajasthali",
          "Belaichhari",
          "Naniyachar",
          "Kawkhali",
          "Rangamati Sadar",
          "Juraichhari",
          "Bagaichhari",
        ],
      },
    ],
  },
  dhaka: {
    status: {
      code: 200,
      message: "ok",
      date: "Sat, 20 Jan 2024 08:32:11 GMT",
    },
    data: [
      {
        _id: "faridpur",
        district: "Faridpur",
        coordinates: "23.5424, 89.6309",
        upazilla: [
          "Boalmari",
          "Faridpur Sadar",
          "Alfadanga",
          "Charbhadrasan",
          "Madhukhali",
          "Saltha",
          "Sadarpur",
          "Nagarkanda",
          "Bhanga",
        ],
      },
      {
        _id: "gazipur",
        district: "Gazipur",
        coordinates: "24.0958, 90.4125",
        upazilla: [
          "Kapasia",
          "Kaliganj",
          "Kaliakair",
          "Sreepur",
          "Gazipur Sadar",
        ],
      },
      {
        _id: "gopalganj",
        district: "Gopalganj",
        coordinates: "23.0488, 89.8879",
        upazilla: [
          "Tungipara",
          "Kashiani",
          "Muksudpur",
          "Kotalipara",
          "Gopalganj Sadar",
        ],
      },
      {
        _id: "kishoreganj",
        district: "Kishoreganj",
        coordinates: "24.4260, 90.9821",
        upazilla: [
          "Kishoreganj Sadar",
          "Itna",
          "Austagram",
          "Pakundia",
          "Hossainpur",
          "Tarail",
          "Bhairab",
          "Mithamain",
          "Bajitpur",
          "Kuliarchar",
          "Katiadi",
          "Nikli",
          "Karimganj",
        ],
      },
      {
        _id: "madaripur",
        district: "Madaripur",
        coordinates: "23.2393, 90.1870",
        upazilla: ["Shibchar", "Madaripur Sadar", "Kalkini", "Rajoir"],
      },
      {
        _id: "manikganj",
        district: "Manikganj",
        coordinates: "23.8617, 90.0003",
        upazilla: [
          "Manikgonj Sadar",
          "Shivalaya",
          "Ghior",
          "Harirampur",
          "Singair",
          "Daulatpur",
          "Saturia",
        ],
      },
      {
        _id: "munshiganj",
        district: "Munshiganj",
        coordinates: "23.4981, 90.4127",
        upazilla: [
          "Sreenagar",
          "Gazaria",
          "Tongibari",
          "Sirajdikhan",
          "Munshiganj Sadar",
          "Lohajang",
        ],
      },
      {
        _id: "narayanganj",
        district: "Narayanganj",
        coordinates: "23.7147, 90.5636",
        upazilla: [
          "Rupganj",
          "Bandar",
          "Sonargaon",
          "Araihazar",
          "Narayanganj Sadar",
        ],
      },
      {
        _id: "narsingdi",
        district: "Narsingdi",
        coordinates: "24.1344, 90.7860",
        upazilla: [
          "Palash",
          "Belabo",
          "Narsingdi Sadar",
          "Raipura",
          "Monohardi",
          "Shibpur",
        ],
      },
      {
        _id: "rajbari",
        district: "Rajbari",
        coordinates: "23.7151, 89.5875",
        upazilla: [
          "Baliakandi",
          "Rajbari Sadar",
          "Goalandaghat",
          "Pangsha",
          "Kalukhali",
        ],
      },
      {
        _id: "shariatpur",
        district: "Shariatpur",
        coordinates: "23.2423, 90.4348",
        upazilla: [
          "Damudya",
          "Gosairhat",
          "Shariatpur Sadar",
          "Zajira",
          "Naria",
          "Bhedarganj",
        ],
      },
      {
        _id: "tangail",
        district: "Tangail",
        coordinates: "24.3917, 89.9948",
        upazilla: [
          "Kalihati",
          "Nagarpur",
          "Tangail Sadar",
          "Sakhipur",
          "Bhuapur",
          "Madhupur",
          "Gopalpur",
          "Mirzapur",
          "Delduar",
          "Dhanbari",
          "Ghatail",
          "Basail",
        ],
      },
    ],
  },
  khulna: {
    status: {
      code: 200,
      message: "ok",
      date: "Sat, 20 Jan 2024 08:32:12 GMT",
    },
    data: [
      {
        _id: "bagerhat",
        district: "Bagerhat",
        coordinates: "22.6602, 89.7895",
        upazilla: [
          "Sarankhola",
          "Bagerhat Sadar",
          "Chitalmari",
          "Fakirhat",
          "Morrelganj",
          "Mongla",
          "Rampal",
          "Mollahat",
          "Kachua",
        ],
      },
      {
        _id: "chuadanga",
        district: "Chuadanga",
        coordinates: "23.6161, 88.8263",
        upazilla: ["Damurhuda", "Chuadanga Sadar", "Alamdanga", "Jibannagar"],
      },
      {
        _id: "jashore",
        district: "Jashore",
        coordinates: "23.1634, 89.2182",
        upazilla: [
          "Manirampur",
          "Sharsha",
          "Jhikargachha",
          "Jashore Sadar",
          "Bagherpara",
          "Chaugachha",
          "Keshabpur",
          "Abhaynagar",
        ],
      },
      {
        _id: "jhenaidah",
        district: "Jhenaidah",
        coordinates: "23.5450, 89.1726",
        upazilla: [
          "Kaliganj",
          "Harinakunda",
          "Kotchandpur",
          "Maheshpur",
          "Jhenaidah Sadar",
          "Shailkupa",
        ],
      },
      {
        _id: "khulna",
        district: "Khulna",
        coordinates: "22.6738, 89.3967",
        upazilla: [
          "Batiaghata",
          "Koyra",
          "Phultala",
          "Dumuria",
          "Dighalia",
          "Paikgachha",
          "Rupsha",
          "Terokhada",
          "Dacope",
        ],
      },
      {
        _id: "kushtia",
        district: "Kushtia",
        coordinates: "23.8907, 89.1099",
        upazilla: [
          "Daulatpur",
          "Kumarkhali",
          "Mirpur",
          "Khoksa",
          "Bheramara",
          "Kushtia Sadar",
        ],
      },
      {
        _id: "magura",
        district: "Magura",
        coordinates: "23.4290, 89.4364",
        upazilla: ["Shalikha", "Sreepur", "Mohammadpur", "Magura Sadar"],
      },
      {
        _id: "meherpur",
        district: "Meherpur",
        coordinates: "23.8052, 88.6724",
        upazilla: ["Mujibnagar", "Meherpur Sadar", "Gangni"],
      },
      {
        _id: "narail",
        district: "Narail",
        coordinates: "23.1163, 89.5840",
        upazilla: ["Lohagara", "Kalia", "Narail Sadar"],
      },
      {
        _id: "satkhira",
        district: "Satkhira",
        coordinates: "22.3155, 89.1115",
        upazilla: [
          "Shyamnagar",
          "Tala",
          "Satkhira Sadar",
          "Assasuni",
          "Kaliganj",
          "Kalaroa",
          "Debhata",
        ],
      },
    ],
  },
  mymensingh: {
    status: {
      code: 200,
      message: "ok",
      date: "Sat, 20 Jan 2024 08:32:13 GMT",
    },
    data: [
      {
        _id: "jamalpur",
        district: "Jamalpur",
        coordinates: "25.0831, 89.7853",
        upazilla: [
          "Baksiganj",
          "Melandaha",
          "Jamalpur Sadar",
          "Dewanganj",
          "Sarishabari",
          "Islampur",
          "Madarganj",
        ],
      },
      {
        _id: "mymensingh",
        district: "Mymensingh",
        coordinates: "24.7539, 90.4073",
        upazilla: [
          "Muktagachha",
          "Haluaghat",
          "Tara Khanda",
          "Dhobaura",
          "Fulbaria",
          "Nandail",
          "Gauripur",
          "Bhaluka",
          "Trishal",
          "Ishwarganj",
          "Mymensingh Sadar",
          "Phulpur",
          "Gafargaon",
        ],
      },
      {
        _id: "netrokona",
        district: "Netrokona",
        coordinates: "24.8103, 90.8656",
        upazilla: [
          "Purbadhala",
          "Mohanganj",
          "Barhatta",
          "Durgapur",
          "Madan",
          "Netrokona Sadar",
          "Khaliajuri",
          "Kalmakanda",
          "Kendua",
          "Atpara",
        ],
      },
      {
        _id: "sherpur",
        district: "Sherpur",
        coordinates: "25.0746, 90.1495",
        upazilla: [
          "Nalitabari",
          "Jhenaigati",
          "Sreebardi",
          "Nakla",
          "Sherpur Sadar",
        ],
      },
    ],
  },
  rajshahi: {
    status: {
      code: 200,
      message: "ok",
      date: "Sat, 20 Jan 2024 08:32:13 GMT",
    },
    data: [
      {
        _id: "bogura",
        district: "Bogura",
        coordinates: "24.8510, 89.3697",
        upazilla: [
          "Sherpur",
          "Dhunat",
          "Nandigram",
          "Adamdighi",
          "Shibganj",
          "Sariakandi",
          "Bogura Sadar",
          "Gabtali",
          "Shajahanpur",
          "Kahaloo",
          "Sonatola",
          "Dhupchanchia",
        ],
      },
      {
        _id: "chapai nawabganj",
        district: "Chapai Nawabganj",
        coordinates: "24.7413, 88.2912",
        upazilla: [
          "Nachole",
          "Gomastapur",
          "Shibganj",
          "Bholahat",
          "Chapai Nawabganj Sadar",
        ],
      },
      {
        _id: "joypurhat",
        district: "Joypurhat",
        coordinates: "25.0947, 89.0945",
        upazilla: [
          "Joypurhat Sadar",
          "Akkelpur",
          "Panchbibi",
          "Kalai",
          "Khetlal",
        ],
      },
      {
        _id: "naogaon",
        district: "Naogaon",
        coordinates: "24.9132, 88.7531",
        upazilla: [
          "Naogaon Sadar",
          "Porsha",
          "Manda",
          "Patnitala",
          "Atrai",
          "Badalgachhi",
          "Mohadevpur",
          "Dhamoirhat",
          "Niamatpur",
          "Sapahar",
          "Raninagar",
        ],
      },
      {
        _id: "natore",
        district: "Natore",
        coordinates: "24.4102, 89.0076",
        upazilla: [
          "Bagatipara",
          "Natore Sadar",
          "Lalpur",
          "Singra",
          "Gurudaspur",
          "Naldanga",
          "Baraigram",
        ],
      },
      {
        _id: "pabna",
        district: "Pabna",
        coordinates: "24.1585, 89.4481",
        upazilla: [
          "Ishwardi",
          "Atgharia",
          "Pabna Sadar",
          "Santhia",
          "Faridpur",
          "Chatmohar",
          "Bera",
          "Bhangura",
          "Sujanagar",
        ],
      },
      {
        _id: "rajshahi",
        district: "Rajshahi",
        coordinates: "24.3733, 88.6049",
        upazilla: [
          "Charghat",
          "Paba",
          "Bagmara",
          "Durgapur",
          "Godagari",
          "Tanore",
          "Bagha",
          "Puthia",
          "Mohanpur",
        ],
      },
      {
        _id: "sirajganj",
        district: "Sirajganj",
        coordinates: "24.3141, 89.5700",
        upazilla: [
          "Kazipur",
          "Chauhali",
          "Sirajganj Sadar",
          "Tarash",
          "Belkuchi",
          "Ullahpara",
          "Shahjadpur",
          "Kamarkhanda",
          "Raiganj",
        ],
      },
    ],
  },
  rangpur: {
    status: {
      code: 200,
      message: "ok",
      date: "Sat, 20 Jan 2024 08:32:14 GMT",
    },
    data: [
      {
        _id: "dinajpur",
        district: "Dinajpur",
        coordinates: "25.6279, 88.6332",
        upazilla: [
          "Biral",
          "Hakimpur",
          "Chirirbandar",
          "Bochaganj",
          "Kaharole",
          "Birganj",
          "Ghoraghat",
          "Birampur",
          "Dinajpur Sadar",
          "Nawabganj",
          "Khansama",
          "Parbatipur",
          "Phulbari",
        ],
      },
      {
        _id: "gaibandha",
        district: "Gaibandha",
        coordinates: "25.3297, 89.5430",
        upazilla: [
          "Gobindaganj",
          "Palashbari",
          "Sundarganj",
          "Gaibandha Sadar",
          "Sadullapur",
          "Phulchhari",
          "Sughatta",
        ],
      },
      {
        _id: "kurigram",
        district: "Kurigram",
        coordinates: "25.8072, 89.6295",
        upazilla: [
          "Nageshwari",
          "Char Rajibpur",
          "Kurigram Sadar",
          "Phulbari",
          "Rajarhat",
          "Ulipur",
          "Bhurungamari",
          "Raomari",
          "Chilmari",
        ],
      },
      {
        _id: "lalmonirhat",
        district: "Lalmonirhat",
        coordinates: "25.9923, 89.2847",
        upazilla: [
          "Kaliganj",
          "Hatibandha",
          "Patgram",
          "Aditmari",
          "Lalmonirhat Sadar",
        ],
      },
      {
        _id: "nilphamari",
        district: "Nilphamari",
        coordinates: "25.8483, 88.9414",
        upazilla: [
          "Kishoreganj",
          "Domar",
          "Nilphamari Sadar",
          "Jaldhaka",
          "Saidpur",
          "Dimla",
        ],
      },
      {
        _id: "panchagarh",
        district: "Panchagarh",
        coordinates: "26.2709, 88.5952",
        upazilla: ["Tetulia", "Boda", "Debiganj", "Atwari", "Panchagarh Sadar"],
      },
      {
        _id: "rangpur",
        district: "Rangpur",
        coordinates: "25.7468, 89.2508",
        upazilla: [
          "Badarganj",
          "Mithapukur",
          "Pirganj",
          "Kaunia",
          "Taraganj",
          "Gangachhara",
          "Pirgachha",
          "Rangpur Sadar",
        ],
      },
      {
        _id: "thakurgaon",
        district: "Thakurgaon",
        coordinates: "26.0418, 88.4283",
        upazilla: [
          "Haripur",
          "Ranisankail",
          "Baliadangi",
          "Thakurgaon Sadar",
          "Pirganj",
        ],
      },
    ],
  },
  sylhet: {
    status: {
      code: 200,
      message: "ok",
      date: "Sat, 20 Jan 2024 08:32:14 GMT",
    },
    data: [
      {
        _id: "habiganj",
        district: "Habiganj",
        coordinates: "24.8103, 90.8656",
        upazilla: [
          "Sayestaganj",
          "Madhabpur",
          "Lakhai",
          "Ajmiriganj",
          "Nabiganj",
          "Habiganj Sadar",
          "Bahubal",
          "Chunarughat",
          "Baniyachong",
        ],
      },
      {
        _id: "moulvibazar",
        district: "Moulvibazar",
        coordinates: "24.8103, 90.8656",
        upazilla: [
          "Moulvibazar Sadar",
          "Sreemangal",
          "Kulaura",
          "Kamalganj",
          "Juri",
          "Barlekha",
          "Rajnagar",
        ],
      },
      {
        _id: "sunamganj",
        district: "Sunamganj",
        coordinates: "25.0715, 91.3992",
        upazilla: [
          "Derai",
          "Sullah",
          "Dakshin Sunamganj",
          "Tahirpur",
          "Jamalganj",
          "Chhatak",
          "Dharamapasha",
          "Bishwamvarpur",
          "Jagannathpur",
          "Sunamganj Sadar",
          "Dowarabazar",
        ],
      },
      {
        _id: "sylhet",
        district: "Sylhet",
        coordinates: "24.8993, 91.8700",
        upazilla: [
          "Companigonj",
          "Osmani Nagar",
          "Golapganj",
          "Jaintiapur",
          "Balaganj",
          "Gowainghat",
          "Dakshin Surma",
          "Kanaighat",
          "Bishwanath",
          "Sylhet Sadar",
          "Fenchuganj",
          "Zakiganj",
          "Beanibazar",
        ],
      },
    ],
  },
};
